import Head from "next/head";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [terminalInput, setTerminalInput] = useState('')

  // Source: https://stackoverflow.com/questions/37440408/how-to-detect-esc-key-press-in-react-and-how-to-handle-it
  // With added functionality
  const keystrokeDetection = useCallback((event) => {
    const key = event.key
    const ignoreList = ['Shift', 'Control', 'Alt', 'Escape', 'Tab', 'Home', 'Delete', 'End', 'Meta']

    function handleInput() {
      if (!ignoreList.includes(key)) {
        setTerminalInput(prev => prev.concat(key))
      }
    }

    function handleSubmission() {
      
    }

    switch (key) {
      case 'Enter':
        handleSubmission()
        break
      case 'Backspace':
        setTerminalInput(prev => prev.slice(0, -1))
        break
      case 'Space':
        setTerminalInput(prev => prev.concat(' '))
        break
      default:
        handleInput()
    }
  }, []);

  useEffect(() => {
    document.addEventListener("keydown", keystrokeDetection, false);

    return () => {
      document.removeEventListener("keydown", keystrokeDetection, false);
    };
  }, []);
  
  return (
    <div>
      <Head>
        <title>Brendan Stander</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"></link> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home}>
        {/* Are <li> list items outdated? Gonna give it a pass for now.*/}
        <h3>&#62; BRENDAN STANDER</h3>
        <h3>&#62; ===============</h3>
        <h3>&#62; my clich&#233;-looking portfolio website</h3>
        <h3>&#62;</h3>
        <div className="link-area">
          <h3 className="main-link">
            &#62;{" "}
            <Link passHref href={"/portfolio"}>
              <span>
                view portfolio<span className="blink-link">_</span>
              </span>
            </Link>
          </h3>
          <h3 className="main-link">
            &#62;{" "}
            <Link passHref href={"/about-me"}>
              <span>
                about me<span className="blink-link">_</span>
              </span>
            </Link>
          </h3>
          <h3 className="main-link">
            &#62;{" "}
            <Link passHref href={"/tangents"}>
              <span>
                tangents<span className="blink-link">_</span>
              </span>
            </Link>
          </h3>
          <h3 className="main-link">
            &#62;{" "}
            <Link passHref href={"/contact-me"}>
              <span>
                contact me<span className="blink-link">_</span>
              </span>
            </Link>
          </h3>
          <h3>
            &#62; {terminalInput}<span className="blinker">_</span>
          </h3>
        </div>
      </div>
    </div>
  );
}
